---
- name: Install microk8s
  become: yes
  community.general.snap:
    name: microk8s
    classic: yes

- name: Microk8s status
  become: yes
  shell: microk8s.status --wait-ready
  args:
    executable: /bin/bash